<a href="https://colab.research.google.com/github/Astroneko404/TF_Study_Note/blob/master/Tensorflow%E6%95%99%E5%AD%A6%E6%B5%8B%E8%AF%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 基础加法，乘法

In [1]:
import tensorflow as tf

A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

C = A + B # C = tf.add(A, B)
D = A * B

print(C)
print(D)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


##### matmul vs multiply

In [2]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5], [6]])

print(tf.matmul(A, B))
print(tf.multiply(A, B))

tf.Tensor(
[[17]
 [39]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[ 5 10]
 [18 24]], shape=(2, 2), dtype=int32)


#### 利用GradientTape求导

In [3]:
x = tf.Variable(initial_value=3.)

with tf.GradientTape() as tape:
  y = x**2  # y = tf.square(x)

y_grad = tape.gradient(y, x)
print(y)
print(y_grad)

tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [4]:
X = tf.constant([[1., 2.], [3., 4.]])
y = tf.constant([[1.], [2.]])
w = tf.Variable(initial_value=[[1.], [2.]])
b = tf.Variable(initial_value=1.)

# 计算L(w, b)关于w, b的偏导数
with tf.GradientTape() as tape:
    L = tf.reduce_sum(tf.square(tf.matmul(X, w) + b - y))
w_grad, b_grad = tape.gradient(L, [w, b])        
print(L, w_grad, b_grad)

tf.Tensor(125.0, shape=(), dtype=float32) tf.Tensor(
[[ 70.]
 [100.]], shape=(2, 1), dtype=float32) tf.Tensor(30.0, shape=(), dtype=float32)
